-- ==========================================
-- dCMMS PostgreSQL Initialization
-- ==========================================
-- Runs once, via docker-entrypoint-initdb.d, when the Postgres container
-- creates its data directory.
--
-- This file used to create 10 tables, ~40 indexes, 7 enum types, 8 triggers
-- and a seeded super_admin. That made it a second, conflicting source of
-- schema truth: the drizzle baseline uses CREATE TABLE IF NOT EXISTS, so
-- those 10 tables silently kept this file's definitions and drizzle's
-- versions never applied. `assets.metadata` being text here and jsonb in
-- schema.ts is the drift that became FE-BUG-04.
--
-- The schema now lives in exactly one place: backend/drizzle/, applied by
-- `npm --prefix backend run db:migrate`. See
-- docs/architecture/adrs/ADR-004-migration-strategy.md (REV-011).
--
-- Nothing is needed here any more — the migrations create their own
-- extensions. Kept as a deliberately empty file so the compose mount does
-- not break.

COMMENT ON DATABASE dcmms IS 'dCMMS - schema managed by backend/drizzle (see ADR-004)';
